Ace.el('#demo').ace('form', {
  // Please changed to 'public' once you go LIVE.
  server: 'test',
  // Please update with the AuthKey provided to you by an Account Manager.
  authkey: '52ab62e8-f9fc-4986-8a4e-dc10573c21bd',

  // show and enable pager functionality
  pagerShow: true,
  pagerEnabled: true,

  // submit whole form with last page
  // instead each page submission one-by-one
  submit: 'lastpage',

  pages: [
    {label: 'Page 1', fields: ['Program', 'Concentration']},

    {
      label: 'Page 2', fields: [
      'HighSchoolGraduationYear', 'HighestLevelOfEducation',
      'DegreeLevel', 'LearningEnvironment', 'MilitaryAffiliation']
    },

    // Below are settings for auto-generated page
    // where you can specify common page attributes.
    // Since a final page with remaining fields
    // will always be generated by default,
    // so this item is not really needed here.
    {
      label: 'Personal Information',
      fields: 'auto',
      classname: 'remaining-fields'
    },

    {
      label: 'Almost done!', fields: ['PostalCode', 'City', 'State'],
      label_submit: 'Submit form now!'
    }

  ],

  fields: {
    LearningEnvironment: {
      // pre-select a checkbox or radio field. Try 'eq:1' value also.
      preselect: 'all'
    },
    PostalCode: {
      // mask for US-only postal codes
      mask: '99999',
      // custom validation message
      validation_message: 'Invalid Zip Code',
      // pre-populates a field with specific value.
      stored_values: ['90210']
    },
    State: {
      mask: 'aa'
    },
    EmailAddress: {
      validation_message: 'Invalid Email Address',
      // pre-populates a field with specific value.
      stored_values: ['test@test.com']
    }
  },

  zip: {
    // Auto-prepopulate city/state if zip field has initial value
    autofetch: true
  },

  // Settings for "results" method.
  // This is simplified usage of `form.ace('results', settings)`
  results: {
    // Auto attach and fetch results after form was successfully submitted
    attach: 'auto',

    settings: {
      pagerShow: true,
      pagerEnabled: true,
      pagerCycle: true,

      form: {
        message_submitted: '<h2>Submitted!</h2>',
        attach: 'action', // try 'auto' value also

        // here is result-form instance settings.
        settings: {
          // Hide predefined fields, which was submitted with primary form,
          // or pre-populated with form settings.
          hide_predefined: true,
          pages: [{
            fields: 'auto',
            label_submit: 'Request information'
          }]
        }
      }
    }
  }

// Event trigger on results instance was attached.
}).on('ace-attached-results', function (e, form, results) {

  // All results instance events could be listen here
  results.on('ace-initialized', function (e, results) {});

  // Event trigger on result form instance was attached.
  results.on('ace-attached-form', function (e, results, resultform, result) {

    // All form instance events could be listen here
    resultform.on('ace-initialized', function (e, resultform) {

      // autosubmit result form if all fields are validated already.
      if (resultform.validated()) {
        resultform.actions.fire('form-submit');
      }
    });
  });

});

